Add Starling Staking delegation token asset metadata and image
prax-wallet/registry pull request #38
Opened 2024-05-23 06:10 UTC by plaidfinch

This PR adds the [Starling Staking](https://starlingcyber.net) delegation token and its asset metadata, along with an SVG suitable for use in token display.

2024-05-23 07:30 UTC, hdevalence commented on input/penumbra-testnet-deimos-8.json
> +      "symbol": "Delegation (Starling Staking)",
This should be consistent with the other delegation tokens
```suggestion
      "symbol": "delUM(Starling Staking)",
```

2024-05-23 07:32 UTC, hdevalence commented on input/penumbra-testnet-deimos-8.json
> +          "png": "https://raw.githubusercontent.com/prax-wallet/registry/main/images/starling-staking.svg"
This is an SVG, not a PNG.
```suggestion
          "svg": "https://raw.githubusercontent.com/prax-wallet/registry/main/images/starling-staking.svg"
```

2024-05-23 07:33 UTC, hdevalence requested changes
The symbol for the delegation token should match the auto-generated symbols used in by Prax.

2024-05-23 18:02 UTC, hdevalence approved these changes

2024-05-24 11:01 UTC, grod220 commented
The changeset is not done quite right. Will merge this and open another PR that fixes this and cuts a release 👍 

https://github.com/prax-wallet/registry/blob/main/README.md?plain=1#L44-L46

2024-05-24 11:01 UTC, merged

2024-05-28 09:32 UTC, grod220 commented
Hmm. It kind of feels like it is needed to be done manually given it requires the user to use the changesets CLI to:
- Declare a change that requires a new publish
- Give a summary of that change
- Identify if it was a patch/minor/major

In theory, a github action command could create one manually and use the commit text as the changeset summary and then make another commit with the version bump. Not sure how it would distinguish the level of version bump it needs though 🤔 . Is this the workflow you had in mind though @plaidfinch?